--- 
title: "R：从基础到不太基础 - R: from basics to not so basic"
author: "Sergio Ibarra-Espinosa"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: rstudio/bookdown-demo
description: "From really basics to not so basic R course."
---

# Notes

CHN:

在本课程中，我将尝试用** CHN **和英语** ENG **显示中文内容。

ENG:

In this course, I will try to show the content in Chinese with the words **CHN** and English with **ENG**

# Prerequisites

CHN:

本课程专为从未使用过R并依赖Excel丰富多彩功能的人士而设计。
本课程也适用于Linux用户。
如果您使用时空数据，如矢量（shapefiles）和栅格或网格（.Tiff，NetCDF）。
由于我从未见过任何人使用Windows以外的其他人，偶尔也会使用某些Mac，我不希望对/etc/sources.list进行任何更改以保持更新的R或其他任何内容。

ENG:

This course is designed for people who never used R and relies on the colorful functions of Excel.
This course is also for Linux people.
If you work with spatiotemporal data such as vectors (shapefiles) and raster or gridded (.Tiff, NetCDF).
As I never saw anyone using other than Windows and occasionally some Mac, I`m not expecting any change to /etc/sources.list to keep updated R or anything.


```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown'
), 'packages.bib')
```
